### ISSUE TITLE
5 dot leader rule issues in table of contents

### ISSUE THREAD

**Issue by jcwhittier** [rpspringuel/maine-thesis#15] opened 2018-07-03 19:08 UTC
I've attached a pdf with an example of the issue and a MWE. 
[toc-orphan-mwe.pdf](https://github.com/rpspringuel/maine-thesis/files/2160698/toc-orphan-mwe.pdf)
[toc-orphan-mwe.zip](https://github.com/rpspringuel/maine-thesis/files/2160706/toc-orphan-mwe.zip)

**Comment by rpspringuel** [comment] 2018-07-05 00:25
I'm going out of town tomorrow for a couple of weeks.  I'll look into this when I get back.

**Comment by jcwhittier** [comment] 2018-10-16 21:04
I've update the MWE to show only 4 dots being produced
[toc-orphan-mwe.zip](https://github.com/rpspringuel/maine-thesis/files/2484906/toc-orphan-mwe.zip)
[toc-orphan-mwe.pdf](https://github.com/rpspringuel/maine-thesis/files/2484907/toc-orphan-mwe.pdf)

**Comment by rpspringuel** [comment] 2018-10-16 21:18
Got it.  The issue seems to be specific to pdfTeX because when I use LuaTeX (which is my usual engine) I get 5 dots, as expected.  I'll see if I can't isolate the behavior and make pdfTeX behave better.

**Comment by jcwhittier** [comment] 2018-10-16 21:24
I haven't checked, but I'm wondering if it might be at all related to the `twoside` vs. `unbound` option.

**Comment by rpspringuel** [comment] 2018-10-16 21:31
No, the issue is in [line 873](https://github.com/rpspringuel/maine-thesis/blob/77d3c55e64819e8dce588aa432f5bebb12b3a058/maine-thesis.cls#L873).  That's where the minimum length of the dottedtocline is set and it appears to be just a hair too short for pdfTeX.  I just played with it a bit and found that by increasing it by 0.1mm, pdfTeX produces the appropriate 5-dot minimum (at least for the test case).  My guess is that there's been some minor adjustments in the font kerning tables (which usually have some slight variations between engines, in my experience) and that resulted in this test case showing that things weren't quite right.  I'll have the fix up in a moment (just need to document it).

**Comment by rpspringuel** [comment] 2018-10-16 21:35
Turns out it was already documented (the 5-dot minimum enforcement is relatively new).  So, closed via 86d23324436a05470fb2cc82ef04014b7c8b4ae3.

**Closed as completed by rpspringuel** 2018-10-16 21:35 UTC
